version: '3.8'

services: 
    app:
        build: .
        command: ./wait-for-postgres.sh db ./go-vid-stream
        ports: 
            - 8000:8000
        depends_on: 
            - db
        environment: 
            - DB_PASSWORD=qwerty
    db:
        restart: always
        image: postgres:latest
        volumes: 
            - ./.database/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=qwerty
        ports: 
            - 5432:5432
    s3:
        image: minio/minio:RELEASE.2021-04-06T23-11-00Z
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./storage/storage:/data
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        command: server --address 0.0.0.0:9000 /data